### ISSUE TITLE
issue with use of wave file as ir

### ISSUE THREAD

**Issue by bitkeeper** [HEnquist/camilladsp#109]
While trying the new support of wave files (with camilladsp-0.5.0-linux-armv7.tar.gz) I have an issue with checking the config.
Normally I use this wave file as test for the moOde convertion function.

Which format of wave files are suported/tested ?

Output of the check:
```
pi@moodep4:/usr/share/camilladsp/configs $ camilladsp -c testwav.yml
Config is not valid
Invalid filter 'ir_left'. Reason: Cant read channel 0 of file '/usr/share/camilladsp/coeffs/Cor1S44.wav' which contains 0 channels.
```

mediainfo about the used wave files:
```
pi@moodep4:/usr/share/camilladsp/configs $ mediainfo /usr/share/camilladsp/coeffs/Cor1S44.wav
General
Complete name                            : /usr/share/camilladsp/coeffs/Cor1S44.wav
Format                                   : Wave
File size                                : 1.00 MiB
Duration                                 : 1 s 486 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 5 646 kb/s
Recorded date                            : 1/27/2021
Writing application                      : Unknown

Audio
Format                                   : PCM
Format profile                           : Float
Codec ID                                 : 3
Codec ID/Hint                            : IEEE
Duration                                 : 1 s 486 ms
Bit rate mode                            : Constant
Bit rate                                 : 5 645 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Bit depth                                : 64 bits
Stream size                              : 1.00 MiB (100%)
```

configuration fragment:
```
filters:
  ir_left:
    parameters:
      channel: 0
      filename: /usr/share/camilladsp/coeffs/Cor1S44.wav
      type: Wav
    type: Conv
  ir_right:
    parameters:
      channel: 1
      filename: /usr/share/camilladsp/coeffs/Cor1S44.wav
      type: Wav
    type: Conv
```
