### ISSUE TITLE
$samplerate$ in .yml

### ISSUE THREAD

**Issue by mervinbeng** [HEnquist/camilladsp#128]
I'm close to having a functional equivalent of the old brutefirwrapper via camilladsp, but there is one issue:

In my config file, I tried using the $samplerate$ token so that I can support different sample rates:

```
  mbr_fir_l:
    type: Conv
    parameters:
      type: Wav 
      filename: /etc/drc/hall-phil3_48000.wav
      channel: 0
  mbr_fir_r:
    type: Conv
    parameters:
      type: Wav 
      filename: /etc/drc/hall-phil3_$samplerate$.wav
      channel: 1
```
The first reference was read correctly. The second gave this error:

ERRO Invalid filter 'mbr_fir_r'. Reason: No such file or directory (os error 2), module: camilladsp

Thanks for any pointers on this.
