### ISSUE TITLE
camilladsp stuck in STARTING state 

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camilladsp#160]
to reproduce this bug, you'll need the following setup:

```
---
devices:
  samplerate: 44100
  chunksize: 4096
  capture:
    type: CoreAudio
    device: "BlackHole 16ch"
    channels: 2
    format: FLOAT32LE
  playback:
    type: CoreAudio
    channels: 2
    device: "ADI-2 Pro"
    format: FLOAT32LE
    exclusive: true

```

and the following script:

```
import camilladsp
import sys
import time

c = camilladsp.CamillaConnection("127.0.0.1", 1234)

retry = False
while True:
  try:
    if retry:
      c.connect()
    state = c.get_state()
    if state == camilladsp.ProcessingState.RUNNING:
      [cL, cR] = ["%.2f" % e for e in c.get_capture_signal_rms()]
      [pL, pR] = ["%.2f" % e for e in c.get_playback_signal_rms()]
      print("CAPTURE L:{} R:{} PLAYBACK L: {} R:{}".format(cL, cR, pL, pR))
    if state == camilladsp.ProcessingState.INACTIVE:
      reason = c.get_stop_reason()
      if reason == camilladsp.StopReason.CAPTUREFORMATCHANGE:
        config = c.get_previous_config()
        rate = int(reason.data)
        config['devices']['samplerate'] = rate
        c.set_config(config)
        print("Successfully adjust to the new sample rate!")
    retry = False
  except ConnectionRefusedError as e:
    print("Can't connect to CamillaDSP, is it running? Error:", e)
    retry = True
  except camilladsp.CamillaError as e:
    print("CamillaDSP replied with error:", e)
    retry = True
  except IOError as e:
    print("Websocket is not connected:", e)
    retry = True
  time.sleep(1)
```

and the following output in MPD:

```
audio_output {
 type "osx"
 device "BlackHole 16ch"
 name "BlackHole"
 mixer_type "none"
 hog_device "true"
}
```

How to reproduce:

1. run mpd and play a 44100 file with the above output. 
2. run camillaDSP 
3. run the python script
4. you'll see everything runs fine. 
5. You can change to another track at different sample rate for instance 48000. and you'll see the script adjust the rate automatically. everything still runs fine. 
6. Now switch back to 44100. the script change the rate again and everything runs fine.
7. in MPD, you close the output device, and open again.
8. Play a 44100 file. You'll see everything runs fine. 
9. now here's the bug --- switch to a 48000 track. you'll see MPD still plays music. while the script can change sample rate, itdoes not show level values anymore. if you try to get the state of camillaDSP, it's in STARTING state. 
10. Now switch to 44100 file. MPD plays music. script is able to change sample rate but does not show level values. camillaDSP in STARTING state
8. You can kill camillaDSP, and run camillaDSP again, you'll see again everything works properly.

**Comment by Wang-Yue** [comment]
Notice the reason the above bug occurs is because the playback device is hogged by another process(mpd in this case). remove the  `hog_device "true"` and the bug will not occur. But there's nothing to prevent a process capture to an already hogged device, and above step 2-8 and 11 shows it's completely possible.

**Comment by HEnquist** [comment]
Thanks for reporting! I'll take a look.

**Comment by HEnquist** [comment]
Tried this but having a hard time with MPD (I have never used it before). I also seem to have hit the bug that gives choppy sound with MPD+BlackHole.. (https://github.com/ExistentialAudio/BlackHole/issues/273)

**Comment by Wang-Yue** [comment]
Lemme try (a not so good example) to use only camillaDSP instead. 

still keep the above python script and save it as monitor.py. 

Now, prepare three camillaDSP configs:

the main file main.yml:
```
---
devices:
  samplerate: 44100
  chunksize: 4096
  capture:
    type: CoreAudio
    device: "BlackHole 16ch"
    channels: 2
    format: FLOAT32LE
  playback:
    type: CoreAudio
    channels: 2
    device: "MacBook Pro Speakers"
    format: FLOAT32LE
    exclusive: true
```
the 44100 playback test 44100.yml: 

```
---
devices:
  samplerate: 44100
  chunksize: 4096
  playback:
    type: CoreAudio
    device: "BlackHole 16ch"
    channels: 1
    format: FLOAT32LE
    exclusive: true
  capture:
    type: CoreAudio
    channels: 1
    device: "MacBook Pro Microphone"
    format: FLOAT32LE
```
the 48000 playback test 48000.yml: 
```
---
devices:
  samplerate: 48000
  chunksize: 4096
  playback:
    type: CoreAudio
    device: "BlackHole 16ch"
    channels: 1
    format: FLOAT32LE
    exclusive: true
  capture:
    type: CoreAudio
    channels: 1
    device: "MacBook Pro Microphone"
    format: FLOAT32LE
```

procedure to reproduce:

1. `./camilladsp main.yml -l debug --port 1234 --wait`
2. `python3 monitor.py`
3. Go to Audio Midi Setup. Select the BlackHole device. notice you can adjust sample rate from 44100 to 48000 and the script will adjust sample rate for camilladsp. Everything still runs fine. 
4. Now adjust the sample rate back to 44100. Everything still runs fine.
5. `./camilladsp 44100.yml`. Everything runs fine. This proves camillaDSP is able to capture from a hogged device.
6. kill the program in step 5 by Ctrl + C
5. `./camilladsp 48000.yml`. bug occurs (script is able to switch camillaDSP's sample rate, but camillaDSP is stuck in STARTING mode)
6. kill the camilladsp in step 1. change main.yml's sample rate to 48000 manually. restart it by repeating step 1. Everything runs fine again.
