### ISSUE TITLE
Slowdown of biquads from subnormal numbers 

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camilladsp#175]
I encountered a different busy loop in `CamillaDSP 1.0.0-alpha5` on macOS again and is reproducible. 
One just need a pipeline with a lot of biquad filters such as the following:

```
---
devices:
  samplerate: 192000
  chunksize: 4096
  enable_rate_adjust: true
  capture:
    type: CoreAudio
    device: "BlackHole 16ch"
    channels: 2
    format: FLOAT32LE
  playback:
    type: CoreAudio
    channels: 2
    device: "DX3 Pro+"
    format: FLOAT32LE
    exclusive: true

filters:

# Headphone EQ
# oratory1990 - HD650

  band_1:
    parameters:
      freq: 20.0
      gain: 4.0
      q: 1.1
      type: Peaking
    type: Biquad
  band_2:
    parameters:
      freq: 97.0
      gain: -2.4
      q: 0.7
      type: Peaking
    type: Biquad
  band_3:
    parameters:
      freq: 105.0
      gain: 5.5
      q: 0.71
      type: Lowshelf
    type: Biquad
  band_4:
    parameters:
      freq: 215.0
      gain: -1.8
      q: 1.1
      type: Peaking
    type: Biquad
  band_5:
    parameters:
      freq: 1300.0
      gain: -1.4
      q: 1.5
      type: Peaking
    type: Biquad
  band_6:
    parameters:
      freq: 2000.0
      gain: 3.0
      q: 0.71
      type: Highshelf
    type: Biquad
  band_7:
    parameters:
      freq: 2700
      gain: -1.3
      q: 3.0
      type: Peaking
    type: Biquad
  band_8:
    parameters:
      freq: 3250.0
      gain: -3.0
      q: 2.7
      type: Peaking
    type: Biquad
  band_9:
    parameters:
      freq: 5400.0
      gain: -1.6
      q: 3.0
      type: Peaking
    type: Biquad
  band_10:
    parameters:
      freq: 11000.0
      gain: -3.0
      q: 0.71
      type: Highshelf
    type: Biquad
 
pipeline:

- channel: 0
  names:
  - band_1
  - band_2
  - band_3
  - band_4
  - band_5
  - band_6
  - band_7
  - band_8
  - band_9
  - band_10
  type: Filter
- channel: 1
  names:
  - band_1
  - band_2
  - band_3
  - band_4
  - band_5
  - band_6
  - band_7
  - band_8
  - band_9
  - band_10
  type: Filter
```

Now, run 

```
./camilladsp test.yml
```

And you'll notice everything is very normal. On my computer cpu utilization is around 4.3%. 

Great. Now let's make some sound by opening youtube in Chrome and playing youtube music. cpu utilization is similar: around 5%. 

After a few seconds of playing, close the Chrome window. So now nothing is producing sound. wait for 20 seconds. 

You'll notice camilladsp is going wild and using more than 50% CPU processing power. 

Dtrace profiling shows it's continuously processing chunk (doing biuad).
