### ISSUE TITLE
camilladsp crashed (index out of bound)

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camilladsp#177]
backtrace:
```
 RUST_BACKTRACE=full ./camilladsp test.yml
2022-01-18 02:37:02.141354 INFO [src/bin.rs:711] CamillaDSP version 1.0.0-rc1
2022-01-18 02:37:02.141384 INFO [src/bin.rs:712] Running on macos, x86_64
thread 'CoreaudioCapture' panicked at 'range end index 143192 out of range for slice of length 131072', src/coreaudiodevice.rs:756:26
stack backtrace:
   0:        0x11003e7ea - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3f6c67686edecf39
   1:        0x11006b6ab - core::fmt::write::hff834863a5b3044e
   2:        0x110036d2a - std::io::Write::write_fmt::hd31e381c0493437f
   3:        0x11003a075 - std::panicking::default_hook::{{closure}}::h950b42ae6eb53c9e
   4:        0x110039c4e - std::panicking::default_hook::h56726a679b761481
   5:        0x11003a67a - std::panicking::rust_panic_with_hook::hd8618b0e276f4721
   6:        0x11003edee - std::panicking::begin_panic_handler::{{closure}}::had94d844a03b1eef
   7:        0x11003e927 - std::sys_common::backtrace::__rust_end_short_backtrace::h587724d0ec62e9d9
   8:        0x11003a163 - _rust_begin_unwind
   9:        0x11007e12f - core::panicking::panic_fmt::h70f2ab4e46e3f444
  10:        0x11007dfa6 - core::slice::index::slice_end_index_len_fail::h1305af2d78a5c42d
  11:        0x10feadb06 - <camillalib::coreaudiodevice::CoreaudioCaptureDevice as camillalib::audiodevice::CaptureDevice>::start::{{closure}}::hd5e89e3b19fbf270
  12:        0x10fe9c431 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf0156986538a53f0
  13:        0x10fef1397 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h61970d7d72d2d9fd
  14:        0x11003f4b7 - std::sys::unix::thread::Thread::new::thread_start::h5550481d97246be3
  15:     0x7ff80b1424f4 - __pthread_start
2022-01-18 02:37:02.345147 ERROR [src/processing.rs:50] Message channel error: receiving on a closed channel
2022-01-18 02:37:02.345201 INFO [src/bin.rs:410] Playback finished
```
test file:

```
---
devices:
  samplerate: 44100
  chunksize: 4096
  enable_rate_adjust: true
  capture_samplerate: 192000
  enable_resampling: true
  resampler_type: BalancedAsync 
  playback:
    type: File
    filename: "/dev/null"
    channels: 2
    format: FLOAT32LE
  capture:
    type: CoreAudio
    device: "BlackHole 16ch"
    channels: 2
    format: FLOAT32LE

```
