### ISSUE TITLE
Extreme clipping

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [HEnquist/camilladsp#181]
Hello,

I have a very basic config:

```
devices:
  samplerate: 48000
  chunksize: 1024
  capture:
    type: Pulse
    channels: 2
    device: "MySinkTest.monitor"
    format: S16LE
  playback:
    type: Pulse
    channels: 2
    device: "alsa_output.usb-dac01_ac01-01.analog-stereo"
    format: S16LE
```

And as it is there *extreme* clipping. I tried different Amps, DACs, speakers and sources (REW, spotify). The only thing I could find that works is drastically reducing the volume of the source and pushing the AMP. Note that:

- When I push the source directly to the sound card the problem doesn't occur and I get the same volume level as camillaDSP without the distortion
- It used to work and from one day to another it appeared out of the blue
- I use version `CamillaDSP 1.0.0-rc1` downloaded from github
- I see no clipping warning in the output of camilla DSP
- I tried pushing to Alsa and Pulseaudio and get exactly the same result

Any idea what could be happening ?
