### ISSUE TITLE
Unable to use Ctrl+C to terminate the program while a FIFO File input is loaded

### ISSUE THREAD

**Issue by t123yh** [HEnquist/camilladsp#187]
Step to reproduce:

1. Execute `mkfifo test-fifo` on shell
2. Use file capture config:
```
  capture:
    type: File
    channels: 2
    filename: ./test-fifo
    format: S16LE
```
3. Run camilladsp
4. Press Ctrl+C to stop camilladsp. It will not be terminated until data is pumped to that FIFO.
