### ISSUE TITLE
Next11: Rate adjust give unstable buffer level

### ISSUE THREAD

**Issue by HEnquist** [HEnquist/camilladsp#207]
Ping @pavhofman 
The new rate adjust feature of next11 gives a buffer level and rate adjust that oscillate. 
When using the following config:
```
---
devices:
  samplerate: 192000
  chunksize: 4096
  target_level: 4096
  adjust_period: 3
  enable_resampling: true
  enable_rate_adjust: true
  resampler_type: Synchronous
  capture_samplerate: 44100
  playback:
    type: Alsa
    channels: 2
    device: "hw:Loopback,0,5"
    format: S32LE
  capture:
    type: Alsa
    channels: 2
    device: "hw:Loopback,0,1"
    format: S32LE
```

Gives this level and rate (first few minutes after start):
![Screenshot from 2022-05-17 22-03-39](https://user-images.githubusercontent.com/6504678/168900999-082301f5-c776-48f5-b32d-524984e8ac1d.png)
