### ISSUE TITLE
file backend: synchronous resampler cuts samples at the end of stream

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camilladsp#212]
test file: 

```
---
devices:
  samplerate: 96000
  chunksize: 1024
  enable_resampling: true
  resampler_type: Synchronous # or AccurateAsync
  capture_samplerate: 44100
  playback:
    type: File
    channels: 1
    filename: "result.raw"
    format: S16LE
  capture:
    type: File
    channels: 1
    filename: "test.wav"
    format: S16LE
    extra_samples: 1000
```

<img width="236" alt="Screen Shot 2022-05-30 at 0 02 10" src="https://user-images.githubusercontent.com/889340/170876845-e108925a-7658-4ace-8c2f-ae41428d3243.png">

Here's the wave form of 1) original audio 2) audio generated by the above script but with AccurateAsync resampler 3) audio generated by the above script (using FFT). 

the sinc interpolation works well. the fft cuts off the last few samples.
