### ISSUE TITLE
Using CamillaDSP with pipewire

### ISSUE THREAD

**Issue by julien-piet** [HEnquist/camilladsp#246]
Hi,

I've been trying to use camillaDSP with pipewire on archlinux. I tried following the steps in the README (setting up a sink with `pactl`), however I get the following error right after starting camillaDSP as root: 

`Capture error: PulseAudio error: Connection refused, code: 6`

and the following when starting as myself, it sometimes works, sometimes returns

`Capture error: PulseAudio error: Timeout, code: 8`

I have a standard arch install, with the following software versions : 
CamillaDSP: 1.0.3
Pipewire & pipewire-pulse: 1:0.3.60-3

Pipewire's config is the default. The camillaDSP config file is:

```
devices:
  adjust_period: 10
  capture:
    channels: 2
    device: MySink.monitor
    format: S32LE
    type: Pulse
  capture_samplerate: 48000
  chunksize: 512
  enable_rate_adjust: false
  enable_resampling: false
  playback:
    channels: 2
    device: alsa_output.pci-0000_00_1f.3.iec958-stereo
    format: S32LE
    type: Pulse
  queuelimit: 4
  rate_measure_interval: 10
  resampler_type: Synchronous
  samplerate: 48000
  silence_threshold: -60
  silence_timeout: 3
  stop_on_rate_change: false
  target_level: 0
```

Pipewire seems to work otherwise, and I've been able to get camillaDSP working with pulse before, but the intersection of both seems to be the issue. When it does work, the GUI does not see it as online, and I cannot set an active
