### ISSUE TITLE
No Sound with ALSA CDSP Plugin

### ISSUE THREAD

**Issue by HDH666** [HEnquist/camilladsp#380]
I am using the `cdsp` plugin with CamillaDSP, but I am not hearing any sound when attempting to play audio using aplay. Could you help identify what might be wrong with my setup?

### **Configuration Files**
asound.conf

```
pcm.camilladsp {
    type cdsp
    cpath "/usr/local/bin/camilladsp"
    config_out "/home/hdh/config_out.yaml"
    config_in "/home/hdh/1.yaml"
    
    channels 2

    rates = [
        44100 
        48000 
        88200 
        96000
        176400
        192000
        352800
        384000
    ]
}

pcm.!default {
    type plug
    slave.pcm "camilladsp"
}
```
config.yaml
```yaml
devices:
  adjust_period: 3
  samplerate: 48000
  chunksize: 1024
  queuelimit: 1
  enable_rate_adjust: true
  capture:
    type: Alsa
    channels: 2
    device: "hw:EarPods"
    format: S16LE
  playback:
    type: Alsa
    channels: 2
    device: "hw:EarPods"
    format: S16LE

pipeline:
  - channel: 0
    names:
      - preamp
      - eq1
      - eq2
      - eq3
      - eq4
      - eq5
      - eq6
      - eq7
      - eq8
      - eq9
      - eq10
      - eq11
    type: Filter
  - channel: 1
    names:
      - preamp
      - eq1
      - eq2
      - eq3
      - eq4
      - eq5
      - eq6
      - eq7
      - eq8
      - eq9
      - eq10
      - eq11
    type: Filter

filters:
  preamp:
    type: Gain
    parameters:
      gain: -0.2
  eq1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 48.15
      q: 4.428
      gain: -14.40
  eq2:
    type: Biquad
    parameters:
      type: Peaking
      freq: 61.10
      q: 7.387
      gain: 6.10
  eq3:
    type: Biquad
    parameters:
      type: Peaking
      freq: 73.00
      q: 4.345
      gain: -7.40
  eq4:
    type: Biquad
    parameters:
      type: Peaking
      freq: 101.0
      q: 4.204
      gain: -8.70
  eq5:
    type: Biquad
    parameters:
      type: Peaking
      freq: 331.0
      q: 4.166
      gain: -3.70
  eq6:
    type: Biquad
    parameters:
      type: Peaking
      freq: 402.0
      q: 3.978
      gain: -5.90
  eq7:
    type: Biquad
    parameters:
      type: Peaking
      freq: 544.0
      q: 8.100
      gain: -5.50
  eq8:
    type: Biquad
    parameters:
      type: Peaking
      freq: 578.0
      q: 3.609
      gain: 2.30
  eq9:
    type: Biquad
    parameters:
      type: Peaking
      freq: 6937
      q: 1.412
      gain: -2.70
  eq10:
    type: Biquad
    parameters:
      type: Peaking
      freq: 12874
      q: 1.497
      gain: -6.40
  eq11:
    type: Biquad
    parameters:
      type: Peaking
      freq: 17175
      q: 2.897
      gain: -5.00
```
### System Info
Device: Raspberry Pi 4B
OS: Raspberry Pi OS (aarch64)
### Logs
```bash
hdh@hdh-pi:~ $ aplay 1.wav
Playing WAVE '1.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
2024-11-28 15:25:26.918650 INFO [src/bin.rs:683] CamillaDSP version 2.0.3
2024-11-28 15:25:26.918748 INFO [src/bin.rs:684] Running on linux, aarch64
2024-11-28 15:25:26.971754 INFO [src/alsadevice.rs:142] PB: Starting playback from Prepared state
```
### Issue Summary
When using the `aplay` command to play audio files through CamillaDSP, no sound is produced, despite the fact that the CamillaDSP logs indicate that playback has started successfully. However, when I use `aplay -D hw:EarPods 1.wav`, sound is produced.

I've double-checked my configuration files, but I am still unable to get any sound output when routing through CamillaDSP.

Could you please assist with troubleshooting this issue?

**Comment by HDH666** [comment]
The problem was identified as being caused by an incorrect configuration in the capture section of the YAML file. After changing the capture type from Alsa to File with the appropriate settings, the issue was resolved.

### Solution
To fix the issue, update the capture section of your YAML configuration as follows:

```yaml
capture:
  type: File
  channels: 2
  filename: "/dev/stdin"
  format: S16LE
```
