### ISSUE TITLE
Pulse audio playback wrong connection

### ISSUE THREAD

**Issue by ericct** [HEnquist/camilladsp#395]
Hello,

I'm a total beginner, so it may be a usage problem. I was trying to reproduce the tutorial example (to4chan), without success. 
Using CamillaDSP, v3.0.0 on Fedora core 41.

I've tried to simplify and understand the issue. I'm using an even simpler configuration (just copy 2 to 2 channels, but it's the same with the to4chan):

```
---
title: "Dummy"
description: "Dummy"

devices:
  samplerate: 44100
  chunksize: 1024
  capture:
    type: Pulse
    channels: 2
    device: "InputSink.monitor"
    format: S16LE
  playback:
    type: Pulse
    channels: 2
    device: "OutputSink.playback"
    format: S16LE

mixers:
  to2chan:
    description: "Expand 2 channels to... 2"
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: 0
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: 0
            inverted: false

pipeline:
  - type: Mixer
    name: to2chan
```
I've created the pulse audio nodes with

pactl load-module module-null-sink sink-name=OutputSink channels=2 sink_properties=device.description=OutputSink
pactl load-module module-null-sink sink-name=InputSink channels=2 sink_properties=device.description=InputSink

The nodes are created and when connecting to real source and sink it's OK.

I start CamillaDSP with `~/camilladsp/bin/camilladsp config1.yml` It creates 2 new PA nodes CamillaDSP (for input and output), and while the output node has property `target.object` set to OutputSink.playback (as per configuration), it is linked to InputSink.playback.

If I manually correct this, I can have sound, but with a large delay (I'm opening another issue for this separated problem for clarity).

Unfortunately, I have 0 knowledge of PA, Pipewire. So I do not know at which stage it fails. Have you already seen this? Is the CamillaDSP usage correct here?

Thanks!
