### ISSUE TITLE
Resolve relative-paths relative to the config file

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camilladsp#79]
I would like to be able to put my config and filters in one folder and reference the filter files relative to the config file.
E.g.:
- my_config_dir/config.yaml
- my_config_dir/filter.txt
```
filters:
  fir:
    type: Conv
    parameters:
      type: File
      filename: filter.txt
      format: TEXT
```

Currently, one has to use absolute paths or paths relative to the current working dir (usually not the config dir).
Thus moving the files together or renaming the parent directory breaks the config.
Also, when one wants to build and test filters on one PC and then transfer and run them on another machine (e.g. Raspberry Pi), the same folder structure on both machines is necessary.
