### ISSUE TITLE
Peaking filter with negative gain increases volume

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camilladsp#84]
I have a config with a negative peaking filter.
With the filter I get severe clipping:
`Dec 20 01:11:25.059 WARN Clipping detected, 12 samples clipped, peak 128.92933791033744%, module: camillalib::conversions`
I think, this should not be possible.
Without the filter there is no clipping.

This happened on the HDMI output of my Raspi 3B.
I had to set the ALSA volume for the HDMI output to 0dB, otherwise also the config without the filter would clip: `amixer -c 0 sset "HDMI",0 -- 0dB`
Here is the complete config:
```
devices:
  samplerate: 44100
  chunksize: 1024
  queuelimit: 2
  capture:
    type: Stdin
    channels: 2
    format: S16LE
  playback:
    type: Alsa
    channels: 2
    device: "hw:0"
    format: S16LE # supported formats are: S16LE

filters:
  L1:
    type: Biquad
    parameters:
      type: Peaking
      freq: 100
      q: 1
      gain: -10

pipeline:
  - type: Filter
    channel: 0
    names:
      - L1
```
