### ISSUE TITLE
Please provide an Apple Silicon (arm64) binary

### ISSUE THREAD

**Issue by onodera-punpun** [HEnquist/camilladsp#88]
Rust 1.49 should support it now from what I understand: https://maconarm.com/app/rust

**Comment by HEnquist** [comment]
I want to do this, but things aren't completely straightforward. 
The github runners I use to build only have Intel cpus, meaning I need to cross compile. That shouldn't be a big problem in itself. But my mac can't be updated to big sur and cross-compiling for arm on catalina doesn't seem to work. Thus I would need to change the config for the build job, push the changes to github, wait for it to run and probably fail, change something else, push, and so on. This is too frustrating, I'll wait until I can find some working example I can copy from.

**Comment by HEnquist** [comment]
Got a little further. Now I'm stuck until cpal is updated. The current cpal release doesn't build, but I'm guessing the next one will.

**Comment by HEnquist** [comment]
That wasn't correct, the latest version does build if all dependencies are updated (which I had forgotten to do..) and if the full Xcode is installed.
Can you please try camilladsp-macos-test.zip from here: https://github.com/HEnquist/camilladsp/releases/tag/v0.5.0-beta2
Does it run at all? It's not really beta2, more like beta2-and-a-half.

**Comment by HEnquist** [comment]
There is now a test release built also for apple silicon: https://github.com/HEnquist/camilladsp/releases/tag/dummy1
The file is "camilladsp-macos-aarch64.tar.gz"

I don't have any access to a mac with an arm cpu, can someone plese try it and let me know if it is ok?

**Comment by onodera-punpun** [comment]
Seems to work so far, I heard crackling when running the x86 version through rosetta2, which seems to be fixed now

**Comment by onodera-punpun** [comment]
It seems like it downmixes my stereosignal to mono, is my config wrong, or something with the program...?

```yaml
---
devices:
  samplerate: 44100
  chunksize: 1024
  capture:
    type: CoreAudio
    channels: 2
    device: "BlackHole 2ch"
    format: FLOAT32LE
  playback:
    type: CoreAudio
    channels: 2
    device: "DAC01"
    format: FLOAT32LE

filters:
  gain_500:
    type: Biquad
    parameters:
      type: Peaking
      freq: 500
      q: 1.0
      gain: -2.0
  gain_2000:
    type: Biquad
    parameters:
      type: Peaking
      freq: 2000
      q: 1.0
      gain: -1.0
  gain_4000:
    type: Biquad
    parameters:
      type: Peaking
      freq: 4000
      q: 1.0
      gain: -5.0
  gain_8000:
    type: Biquad
    parameters:
      type: Peaking
      freq: 8000
      q: 1.0
      gain: 5.0
  gain_16000:
    type: Biquad
    parameters:
      type: Peaking
      freq: 16000
      q: 1.0
      gain: 1.0

mixers:
  mono:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false
      - dest: 1
        sources:
          - channel: 0
            gain: -6
            inverted: false
          - channel: 1
            gain: -6
            inverted: false

pipeline:
  - type: Mixer
    name: mono
  - type: Filter
    channel: 0
    names:
      - gain_500
      - gain_2000
      - gain_4000
      - gain_8000
      - gain_16000
  - type: Filter
    channel: 1
    names:
      - gain_500
      - gain_2000
      - gain_4000
      - gain_8000
      - gain_16000
```
