### ISSUE TITLE
choppy sound when playing songs using mpd and Blackhole on MacOS

### ISSUE THREAD

**Issue by onodera-punpun** [HEnquist/camilladsp#90]
Continuation from:  https://github.com/HEnquist/camilladsp/issues/88

## Reproduce

Play a flac song using mpd using blackhole and camilladsp as the output. 44.1kHz flacs will be choppy, 48kHz songs won't produce any sound at all.

Interestingly, when there is a YouTube video playing in the background (even muted), the choppyness will be gone. Also when the following setting screen is open the choppyness will be gone, I'm not sure as to why? Maybe it creates a 48kHz stream like a YouTube video does:

<img width="697" alt="image" src="https://user-images.githubusercontent.com/5213535/105543490-1f33cd00-5cfa-11eb-9fe6-c3be0ad9ad43.png">

Also interesting is that playing a 48kHz song in mpd will kill other streams (such as youtube audio) as well.

## System

Mac Mini M1
Big Sur 11.2

The input and output of BlackHole are both set to `44.1kHz, 2ch 32 bit float`, the output of my dac is set to `2ch 16-bit interger, 44.1kHz`, these are all the default values, and I didn't tinker with them.

## Config

```yaml
---
devices:
  samplerate: 44100
  chunksize: 1024
  capture:
    type: CoreAudio
    channels: 2
    device: "BlackHole 2ch"
    format: FLOAT32LE
  playback:
    type: CoreAudio
    channels: 2
    device: "DAC01"
    format: FLOAT32LE

filters:
  gain_500:
    type: Biquad
    parameters:
      type: Peaking
      freq: 500
      q: 1.0
      gain: -2.0
  gain_2000:
    type: Biquad
    parameters:
      type: Peaking
      freq: 2000
      q: 1.0
      gain: -1.0
  gain_4000:
    type: Biquad
    parameters:
      type: Peaking
      freq: 4000
      q: 1.0
      gain: -5.0
  gain_8000:
    type: Biquad
    parameters:
      type: Peaking
      freq: 8000
      q: 1.0
      gain: 5.0
  gain_16000:
    type: Biquad
    parameters:
      type: Peaking
      freq: 16000
      q: 1.0
      gain: 1.0

mixers:
  mono:
    channels:
      in: 2
      out: 2
    mapping:
      - dest: 0
        sources:
          - channel: 0
            gain: -6.0
            inverted: false
      - dest: 1
        sources:
          - channel: 1
            gain: -6.0
            inverted: false

pipeline:
  - type: Mixer
    name: mono
  - type: Filter
    channel: 0
    names:
      - gain_500
      - gain_2000
      - gain_4000
      - gain_8000
      - gain_16000
  - type: Filter
    channel: 1
    names:
      - gain_500
      - gain_2000
      - gain_4000
      - gain_8000
      - gain_16000
```
