### ISSUE TITLE
Mute options behave strangely when applied during playback

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camilladsp#98]
I just implemented the mute options for gain filter and mixer mappings/sources on the develop branch of camillagui and noticed, that all the mute options behave strangely when applied during playback.

Mute on gain filter:
Most of the times, this does not change anything, when applied during playback.
When I restart CDSP, everything works as expected (correctly muted/unmuted).

Mute on Mixer Mappings & Sources:
This happens only with resamplers enabled - I tried sync and fast async.
The behavior is similar between source and destination channels.
Muting individual channels works fine.
However, when all channels are muted, the last channels that were not muted, play a strange noise.
For example, on a stereo setup, muting destination channel 0 works fine. Then muting channel 1 gives strange noise on channel 1. If both channels were unmuted and both are muted at the same time, the noise is on both channels. Unmuting one channel, removes the noise from all channels.

My config:
```
devices:
  adjust_period: 3
  capture:
    channels: 2
    device: CamillaDSP.monitor
    format: S16LE
    type: Pulse
  capture_samplerate: 44100
  chunksize: 1024
  enable_rate_adjust: false
  enable_resampling: true
  playback:
    channels: 2
    device: alsa_output.pci-0000_00_1f.3.iec958-stereo
    format: S32LE
    type: Pulse
  queuelimit: 4
  resampler_type: Synchronous
  samplerate: 44100
  silence_threshold: 0
  silence_timeout: 0
  target_level: 1024
filters:
  Gain:
    parameters:
      gain: 0
      inverted: false
      mute: false
    type: Gain
mixers:
  New Mixer 1:
    channels:
      in: 2
      out: 2
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: -1
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: -1
        inverted: false
        mute: false
pipeline:
- name: New Mixer 1
  type: Mixer
- channel: 0
  names:
  - Gain
  type: Filter
- channel: 1
  names:
  - Gain
  type: Filter
```
